# AegisNet Project Configuration


# Directory containing dataset CSV files
DATA_DIR = "data"

# Filenames for the CIC-IDS-2017 dataset
DATA_FILES = [
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Tuesday-WorkingHours.pcap_ISCX.csv",
    "Wednesday-workingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv",
    "Friday-WorkingHours-Morning.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
]

# Target column name in the dataset
TARGET_COLUMN = "Label"

# Reports directory and plot paths
REPORTS_DIR = "reports"
ACC_PLOT_PATH = "reports/aegisnet_v1_accuracy.png"
LOSS_PLOT_PATH = "reports/aegisnet_v1_loss.png"

# Classification threshold for predictions
CLASSIFICATION_THRESHOLD = 0.90

# Top features for model training (Generated by FeatureEngine)
TOP_FEATURES = [
    "Max Packet Length",
    "Avg Bwd Segment Size",
    "Packet Length Variance",
    "Destination Port",
    "Packet Length Std",
    "Average Packet Size",
    "Bwd Packet Length Max",
    "Bwd Packet Length Std",
    "Total Length of Bwd Packets",
    "Init_Win_bytes_forward",
    "Total Length of Fwd Packets",
    "Subflow Fwd Bytes",
    "Bwd Packet Length Mean",
    "Packet Length Mean",
    "Subflow Bwd Bytes",
    "Fwd Header Length.1",
    "Avg Fwd Segment Size",
    "Fwd Packet Length Max",
    "Bwd Header Length",
    "Subflow Fwd Packets",
    "Fwd Header Length",
    "Fwd IAT Max",
    "Init_Win_bytes_backward",
    "Fwd Packet Length Mean",
    "Flow Bytes/s",
    "Total Fwd Packets",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow Packets/s",
    "Bwd Packets/s",
]

# Scaler save path for preprocessing
SCALER_SAVE_PATH = "models/aegisnet_scaler.joblib"
